version: "3.5"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    # environment:
    #   - DB_HOST=db
    #   - DB_NAME=app
    #   - DB_USER=postgres
    #   - DB_PASS=secretpassword
    #   - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    #   - GMAIL_ACC=${GMAIL_ACC}
    #   - GMAIL_PW=${GMAIL_PW}
    #   - EMAIL_VERIFICATION_OPTION=${EMAIL_VERIFICATION_OPTION:-none}
    #   - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    #   - KHALTI_SECRET_KEY=${KHALTI_SECRET_KEY}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      ahjin_network:
        aliases:
          - app-backend

  db:
    image: postgres:10-alpine
    restart: always
    # ports:
    #   - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - db:/var/lib/postgresql/data

    networks:
      ahjin_network:
        aliases:
          - pg-database

volumes:
  db:
    driver: local

networks:
  ahjin_network:
    name: ahjin_network
