# Generated by Django 4.0.5 on 2022-07-03 07:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price_m', models.FloatField(default=0, help_text='in NPR', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price_a', models.FloatField(default=0, help_text='in Ahjin Coin', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unique_feature', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.URLField(default='https://www.canva.com/design/DAFBndmWLJ4/Wv-N9IjANw4Q8iRiHUyuBw/view?utm_content=DAFBndmWLJ4&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink')),
                ('image2', models.URLField(default='https://www.canva.com/design/DAFBndmWLJ4/Wv-N9IjANw4Q8iRiHUyuBw/view?utm_content=DAFBndmWLJ4&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink')),
                ('image3', models.URLField(default='https://www.canva.com/design/DAFBndmWLJ4/Wv-N9IjANw4Q8iRiHUyuBw/view?utm_content=DAFBndmWLJ4&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink')),
                ('description', models.TextField(blank=True, null=True)),
                ('cat', models.CharField(choices=[('E', 'Electronics'), ('C', 'Clothes'), ('O', 'Others')], max_length=20)),
                ('d_cat', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
