# Generated by Django 4.0.6 on 2022-07-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://www.google.com/imgres?imgurl=https%3A%2F%2Fpngimg.com%2Fuploads%2Fminions%2Fminions_PNG74.png&imgrefurl=https%3A%2F%2Fpngimg.com%2Fimage%2F36307&tbnid=UfhKhpbhSvDGbM&vet=12ahUKEwjm25DZg_b4AhVn_jgGHYFuBHYQMyg-egQIARB3..i&docid=EmCE6LsjyQnloM&w=1022&h=971&q=minions%20image&ved=2ahUKEwjm25DZg_b4AhVn_jgGHYFuBHYQMyg-egQIARB3', max_length=350),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.URLField(default='https://www.google.com/imgres?imgurl=https%3A%2F%2Fpngimg.com%2Fuploads%2Fminions%2Fminions_PNG74.png&imgrefurl=https%3A%2F%2Fpngimg.com%2Fimage%2F36307&tbnid=UfhKhpbhSvDGbM&vet=12ahUKEwjm25DZg_b4AhVn_jgGHYFuBHYQMyg-egQIARB3..i&docid=EmCE6LsjyQnloM&w=1022&h=971&q=minions%20image&ved=2ahUKEwjm25DZg_b4AhVn_jgGHYFuBHYQMyg-egQIARB3', max_length=350),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.URLField(default='https://www.google.com/imgres?imgurl=https%3A%2F%2Fpngimg.com%2Fuploads%2Fminions%2Fminions_PNG74.png&imgrefurl=https%3A%2F%2Fpngimg.com%2Fimage%2F36307&tbnid=UfhKhpbhSvDGbM&vet=12ahUKEwjm25DZg_b4AhVn_jgGHYFuBHYQMyg-egQIARB3..i&docid=EmCE6LsjyQnloM&w=1022&h=971&q=minions%20image&ved=2ahUKEwjm25DZg_b4AhVn_jgGHYFuBHYQMyg-egQIARB3', max_length=350),
        ),
    ]
