# Generated by Django 4.0.5 on 2022-06-17 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price_a_alter_product_price_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('E', 'Electronics'), ('C', 'Clothes'), ('O', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_a',
            field=models.FloatField(default=0, help_text='in Ahjin Coin', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_m',
            field=models.FloatField(default=0, help_text='in NPR', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
