# Generated by Django 4.0.6 on 2022-07-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='http://res.cloudinary.com/sankalpa-sys/image/upload/v1657722684/jw5rqwjldedhnpxjlztc.jpg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.URLField(default='http://res.cloudinary.com/sankalpa-sys/image/upload/v1657722684/jw5rqwjldedhnpxjlztc.jpg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.URLField(default='http://res.cloudinary.com/sankalpa-sys/image/upload/v1657722684/jw5rqwjldedhnpxjlztc.jpg'),
        ),
    ]
