# Generated by Django 4.0.5 on 2022-06-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_review_name_product_numreviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://www.canva.com/design/DAFBndmWLJ4/Wv-N9IjANw4Q8iRiHUyuBw/view?utm_content=DAFBndmWLJ4&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.URLField(default='https://www.canva.com/design/DAFBndmWLJ4/Wv-N9IjANw4Q8iRiHUyuBw/view?utm_content=DAFBndmWLJ4&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.URLField(default='https://www.canva.com/design/DAFBndmWLJ4/Wv-N9IjANw4Q8iRiHUyuBw/view?utm_content=DAFBndmWLJ4&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink'),
        ),
    ]
