# Generated by Django 4.0.5 on 2022-06-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='paymentMethod',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_chosen',
            new_name='productChosen',
        ),
    ]
