# Generated by Django 4.0.5 on 2022-07-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currentAccount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='isRewarded',
            field=models.BooleanField(default=False),
        ),
    ]
