# Generated by Django 4.0.6 on 2022-07-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_currentaccount_order_isrewarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippingAddress',
            field=models.CharField(default='Pokhara', max_length=100),
            preserve_default=False,
        ),
    ]
