# Generated by Django 4.0.5 on 2022-06-30 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_payment_method_order_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 30, 9, 49, 51, 396043, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
