# Generated by Django 4.0.4 on 2022-05-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ahjin_point',
            new_name='ahjin_coin',
        ),
    ]
