# Generated by Django 4.0.4 on 2022-06-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ahjin_coin',
            field=models.FloatField(default=0),
        ),
    ]
