# Generated by Django 4.0.6 on 2022-07-11 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 11, 9, 40, 12, 58476, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
