name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
        - 
          name: Checking the directory
          run: ls -la
        - 
          name: Checking the directory
          run: ls -la ../
        -
          name: Build the Docker image
          run: docker-compose -f docker-compose-prod.yaml build
        -
          name: Perform some test and linting
          run: echo "PERFORMING SOME TEST AND CHECKING LINTING"
        -  
          name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PW }}
        - 
          name: Build and push
          run: docker-compose -f docker-compose-prod.yaml push
